const Images = {
  OnboardingScreen1: require('../assets/images/boardingscreen1.png'),

  OnboardingScreen2: require('../assets/images/boardingscreen2.png'),
  creditIcon:require('../assets/images/credit1.png'),
  OnboardingScreen3: require('../assets/images/boardingscreen3.png'),

  Sooprslogo: require('../assets/images/sooprslogo.png'),
  Sooprsnewlogo: require('../assets/images/sooprsnewlogo.png'),
  ratingStar:require('../assets/images/cart-rating.png'),
  activeTripIcon:require('../assets/images/vendor-logo.png'),
  Clientlogo: require('../assets/images/client.png'),
  grayVerification:require('../assets/images/sheld.png'),
  shieldIcon:require('../assets/images/refund.png'),
  contactus:require('../assets/images/contact-us.png'),
  rightArrowBlue:require('../assets/images/arrow.png'),
  Professionallogo: require('../assets/images/professional.png'),

  backArrow: require('../assets/Icons/backArrow.png'),

  eye: require('../assets/Icons/eye.png'),
  eyec: require('../assets/Icons/eyec.png'),
  downArrowLight: require('../assets/Icons/downArrowLight.png'),

  googleIcon: require('../assets/images/google.png'),
  crossIcon: require('../assets/images/cross.png'),
  lockIcon: require('../assets/images/lockicon.png'),
  checkblue: require('../assets/images/tick.png'),
  homeIcon: require('../assets/Icons/home.png'),
  projectsIcon: require('../assets/images/document.png'),
  emailIcon: require('../assets/Icons/emailIcon.png'),
  phoneIcon: require('../assets/Icons/phoneIcon.png'),
  phoneIcon1: require('../assets/images/create.png'),
  locationIcon: require('../assets/images/address.png'),
  professionalsIcon: require('../assets/Icons/professionals.png'),
  gigsIcon: require('../assets/Icons/gigs.png'),
  accountIcon: require('../assets/Icons/account.png'),
  helloIcon: require('../assets/Icons/hello.png'),
  bellIcon: require('../assets/Icons/bellicon.png'),
  chatIcon: require('../assets/Icons/chatIcon.png'),
  searchIcon: require('../assets/Icons/searchIcon.png'),
  filterIcon: require('../assets/Icons/filterIcon.png'),
  rigthArrowIcon: require('../assets/Icons/rightArrow.png'),
  categoriesOne: require('../assets/Icons/categoriesone.png'),
  categoriesTwo: require('../assets/Icons/categoriestwo.png'),
  categoriesThree: require('../assets/Icons/categoriesthree.png'),
  profileImage: require('../assets/images/profileimage.png'),
  profileImagetwo: require('../assets/images/profileimagetwo.png'),
  topnotchone: require('../assets/images/topnotchone.png'),
  topnotchtwo: require('../assets/images/topnotchtwo.png'),
  femaleImageOne: require('../assets/images/femaleImageone.png'),
  maleImageOne: require('../assets/images/maleImageone.png'),
  professionalslogo: require('../assets/images/professionalslogo.png'),
  helicopterIcon: require('../assets/Icons/helicopterIcon.png'),
  newspaperIcon: require('../assets/Icons/newspaperIcon.png'),
  swipeIcon: require('../assets/Icons/swipeIcon.png'),
  introLogo: require('../assets/images/clientLogo.png'),
  starIcon: require('../assets/Icons/starIcon.png'),
  reviewerone: require('../assets/Icons/reviewerone.png'),
  reviewertwo: require('../assets/Icons/reviewertwo.png'),
  reviewerthree: require('../assets/Icons/reviewerthree.png'),
  chevronRight: require('../assets/Icons/chevronRight.png'),
  favoriteIcon: require('../assets/images/term.png'),
  walletIcon: require('../assets/images/wallet-icon.png'),
  bankIcon: require('../assets/Icons/bankaccount.png'),
  uparrowIcon: require('../assets/Icons/uparrow.png'),
  logoutIcon: require('../assets/images/logout1.png'),
  tickIcon: require('./images/tick.png'),
  identityIcon: require('../assets/Icons/identity.png'),
  nationalityIcon: require('../assets/Icons/nationality.png'),
  leadServicesIcon: require('../assets/Icons/leadservices.png'),
  resumeIcon: require('../assets/Icons/resume.png'),
  imageIcon: require('../assets/images/camera.png'),
  projectStatus: require('../assets/Icons/projectStatus.png'),
  splashLogo: require('../assets/Icons/splashLogo.gif'),
  cancelIcon: require('../assets/Icons/cancel.png'),
  defaultPicIcon: require('../assets/Icons/defaultPic.png'),
  sendIcon: require('../assets/Icons/sendIcon.png'),
  referandearn: require('../assets/images/referandearn.png'),
  referIcon: require('../assets/images/privacy.png'),
  copyIcon: require('../assets/Icons/copyIcon.png'),
  // dileep
  otpBackground: require('./images/OtpBackground.png'),
  callIcon: require('./images/Call.png'),
  whatsAppIcon: require('./images/whatsapp.png'),
  pdf: require('./images/pdf.jpg'),
  refer: require('./images/refer.png'),
  wallet: require('./images/wallet.png'),
  deleteIcon: require('./images/deleteIcon.png'),
  pdfPreview: require('./images/pdfPreview.png'),
  //tabs
  home: require('./images/home.png'),
  projects: require('./images/leadhome.png'),
  chat: require('./images/order-home.png'),
  //new profile icons
  profileDetails: require('./images/appDetails.png'),
  detailsIcon: require('./images/details.png'),
  gigsIcone: require('./images/GigsIcone.png'), 
  privacyPolicyIcone:require('./images/privacyPolicyIcone.png'),
  termAndConditionIcone:require('./images/terms&Condition.png'),
  refundPolicyIcone:require('./images/refundPolicy.png'),
  contactUsIcone:require('./images/ContectUs.png'),
  faqIcone:require('./images/FAQ.png'),
  passwordIcone:require('./images/passwordIcone.png'),
  bankDetailsIcone:require('./images/bankDetails.png'),
manageDetailsIcone:require('./images/ManageDetails.png'),

  settings1: require('./images/settings1.png'),
  support1: require('./images/support1.png'),
  transactions: require('./images/transactions1.png'),
  wallet1: require('./images/wallet1.png'),
  //arrow
  chevRight: require('./images/chevRight.png'),
  add: require('./images/add.png'),
  star: require('./images/star1.png'),
  chatNavigator: require('./images/chatNavigator.png'),
  // client side icons
  education: require('./images/education.png'),
  about: require('./images/about.png'),
  services: require('./images/services.png'),
  experience: require('./images/experience.png'),
  clientCarousel: require('./images/clientCarousel.png'),
  banner1:require('./images/BannerIcone1.png'),
  banner2:require('./images/BannerIcone2.png'),
  banner3:require('./images/BannerIcone3.png'),
  banner4:require('./images/bannerIcone4.png'),
  viewAll: require('./images/viewAll.png'),
  // catId
  graphic: require('./images/graphic.png'),
  dm: require('./images/dm.png'),
  programming: require('./images/programming.png'),
  // Category Icons
  websideDevelopment:require('./images/webDevelopment.png'),
  mobileAppDevelopment:require('./images/mobileDevelopment.png'),
  digitalMarketing:require('./images/digitalmarketing.png'),
  uiUxDesigning:require('./images/Ui_Ux.png'),
  videoEditing:require('./images/videoEditing.png'),
  artificialIntelligence:require('./images/artificialInteligent.png'),
  packersAndMovers:require('./images/packer&Movers.png'),
  corporateEvents:require('./images/corporateEvent.png'),
  healingWellness:require('./images/healling&welleness.png'),
  realEstate:require('./images/realstate.png'),
  businessCounselling:require('./images/businessCounselling.png'),
  dentistEntDermatologist:require('./images/Dentist.png'),
  video: require('./images/video.png'),
  ai: require('./images/ai.png'),
  writing: require('./images/wri.png'),
  photography: require('./images/photography.png'),
  packers: require('./images/packers.png'),
  // subs
  subscription: require('./images/subscription.png'),
  gigIcon: require('./images/gigIcon.png'),
  addIcon: require('./images/addIcon.png'),

  // Blank CheckBox
  blankChackbox: require('./Icons/BlankBox.png'),
  checkedCheckBox: require('./Icons/CheckedCheckBoxIcone.png'),
  ImageSelectContener: require('./images/SelectImageIcone.png'),
  Dropdown: require('./Icons/dropdownIcone.png'),
  filterIcon1: require('./images/Filter.png'),
  dollarIcon: require('./images/dollarSign.png'),
  //empty data
  emptyAcademics: require('./images/addacademics.png'),
  emptyExperience: require('./images/addexperience.png'),
  emptyServices: require('./images/addservices.png'),
  emptySkills: require('./images/addskills.png'),
  nodata: require('./images/nodata.png'),
  service: require('./images/Service247.png'),
  emptyPortfolio: require('./images/manageportfolio.png'),
  // accountIcons
  aboutSooprs: require('./images/aboutsooprsicon.png'),
  bankIcon1: require('./images/bankicon.png'),
  subscription1: require('./images/subscription1.png'),
  mDetailsIcon: require('./images/deleteIcon.png'),
  mAcademics: require('./images/eduicon.png'),
  mPortfolio: require('./images/portfolioicon.png'),
  mServices: require('./images/servicesicon.png'),
  mSkills: require('./images/skillsicon.png'),
  mResume: require('./images/resumeicon.png'),
  mExp: require('./images/expicon.png'),
  mPass: require('./images/passwordicon.png'),
  mPrivacy: require('./images/privacyicon.png'),
  mTc: require('./images/tcicon.png'),
  mRefund: require('./images/refundicon.png'),
  mFaq: require('./images/faqicon.png'),
  mTran: require('./images/transaction.png'),
  drawer: require('./images/drawer.png'),
  mBids: require('./images/placebid.png'),
  emptyChat:require('./images/emptyChat.png'),
  link:require('./images/link.png'),
  outStataionIcon:require('./Icons/OutStation.png'),
  localIcon:require('./Icons/Local.png'),
  AirportIcon:require('./Icons/Airport.png'),
  CalenderIcon:require('./images/timer.png'),
  carIcon:require('./Icons/Car.png'),
  UserRoundIcon:require('./Icons/user-round.png'),
  editButton:require('./images/editbutton.png'),
};

export default Images;
